spring.resources.chain.cache: false

server.port: 8080

logging:
  level:
    org.hibernate: WARN
    org.springframework.boot.autoconfigure.logging: ERROR
    org.springframework: WARN
    org.springframework.web.client: INFO
    org.springframework.security: INFO
    org.springframework.security.web: INFO
    org.aspectj: INFO
    io.mikael: DEBUG

server.error.include-stacktrace: always

spring:
  mustache.suffix: .mustache
  datasource:
    url: "jdbc:postgresql:retailexpert"
    username: "mikael"
    password: "mikael"
    platform: postgresql
    driverClassName: org.postgresql.Driver
